name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy Installation
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          which trivy
          trivy --version

      - name: Trivy FS Scan
        run: |
          chmod +x $(which trivy)
          trivy fs --format table -o fs-report.json .

      - name: Gitleaks Installation
        run: |
          sudo apt update
          sudo apt install gitleaks -y
          which gitleaks
          gitleaks version

      - name: Gitleaks Code Scan
        run: |
          chmod +x $(which gitleaks)
          gitleaks detect --source . --report-path=gitleaks-report.json --format=json
